---
title: "An Introduction to the leaflet Package"
author: "Joe Cheng"
date: "`r Sys.Date()`"
output:
  knitr:::html_vignette:
    toc: yes
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{An Introduction to the leaflet Package}
---

[Leaflet](http://leafletjs.com) is an open-source JavaScript library for
interactive maps. [Shiny](http://rstudio.com/shiny) is an open-source R
framework for interactive web apps.

This R package makes it easy to integrate and control Leaflet maps from Shiny
applications. [Here's an example
application](http://glimmer.rstudio.com/jcheng/leaflet-demo) (see
`system.file('examples/population', package = 'leaflet')` for the source).

# Functions

Use the two functions `leafletMap()` and `createLeafletMap()` from your Shiny
app to create Leaflet maps.

```r
# in ui.R
leafletMap(
  outputId, width, height,
  initialTileLayer = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
  initialTileLayerAttribution = HTML(
    '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors,
    <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
  ),
  options = NULL
)

# in server.R
createLeafletMap(session, outputId)
```

# Methods

The following are methods that can be called on the map object that is created
using `createLeafletMap()`. For example:

```r
map <- createLeafletMap(session, "myMap")
map$setView(0, 0, 8)
```

All of the methods that add something to the map take a `layerId` parameter.
This `layerId` is optional but useful for several purposes:

- Calling the same add function with the same `layerId` value will replace the
  old layer instead of just adding a new one
- You can call `removePopup()`, `removeMarker()`, or `removeShape()` with a
  `layerId` to remove the old layer
- You will need a `layerId` to subscribe to events. See Events section below.

Below is a list of currently available methods:

```{r echo=FALSE, comment=''}
library(leaflet)
res <- capture.output(str(unclass(createLeafletMap(list(output = list()), 'foo'))))
cat(gsub(':function ', '', res[-1]), sep = '\n')
```

For methods that have the `options` and `eachOptions` arguments: `options` is a
list of [marker options](http://leafletjs.com/reference.html#marker-options)
that will be applied to all of the markers; `eachOptions` is the same except
that each option value can be a vector, where each element corresponds to a
single marker (recycling will be used if necessary). In most cases, if the
lengths of arguments are not equal, the shorter arguments will be recycled.

Detailed documentation for all methods:

## setView()

```r
setView(lat, lng, zoom, forceReset = FALSE)
```

Sets the center and zoom level of the map. `forceReset` will completely reset
the map view, without animations.

## fitBounds()

```r
fitBounds(lat1, lng1, lat2, lng2)
```

Modifies the center and zoom level of the map such that the specified bounds are
visible.

## addMarker()

```r
addMarker(lat, lng, layerId = NULL, options = list(), eachOptions = list())
```

Adds markers at the designated points. The number of markers added will be the
maximum length of `lat`, `lng`, and `layerId` (if provided).

Three events are supported in markers: `click`, `mouseover`, and `mouseout`.
When these events occur, we can get the `layerId`, latitude, and longitude of
the cursor as a list of the form `list(layerId, lat, lng)`. These lists can be
obtained via `input$MAPID_marker_click`, `input$MAPID_marker_mouseover`, and
`input$MAPID_marker_mouseout`, respectively, where `MAPID` is the id of the map
provided in `leafletMap()`.

## addCircleMarker()

```r
addCircleMarker(lat, lng, radius, layerId = NULL, options = list(), eachOptions = list())
```

Adds circle markers. Circle markers are like circles, but their pixel radius
remains constant as the user zooms in and out.

The number of circle markers added will be the maximum length of `lat`, `lng`,
`radius`, and `layerId`. The `radius` argument is specified in pixels.

Events supported: `input$MAPID_marker_click`, `input$MAPID_marker_mouseover`,
and `input$MAPID_marker_mouseout`.

## addCircle()

```r
addCircle(lat, lng, radius, layerId = NULL, options = list(), eachOptions = list())
```

Adds circle overlays to the map. The number of circle overlays added will be the
maximum length of `lat`, `lng`, `radius`, and `layerId`. The `radius` argument
is specified in meters.

Events supported: `input$MAPID_shape_click`, `input$MAPID_shape_mouseover`,
and `input$MAPID_shape_mouseout`.

## addRectangle()

```r
addRectangle(lat1, lng1, lat2, lng2, layerId = NULL, options = list(), eachOptions = list())
```

Adds rectangular overlays to the map. The number of rectangles added will be the
maximum length of `lat1`, `lng1`, `lat2`, `lng2`, and `layerId`.

Events supported: `input$MAPID_shape_click`, `input$MAPID_shape_mouseover`,
and `input$MAPID_shape_mouseout`.

## addPolygon()

```r
addPolygon(lat, lng, layerId, options, defaultOptions)
```

Adds polygon overlays to the map. `lat` and `lng` encode successive points of
each polygon; the end of a polygon is specified with (`NA`, `NA`). (This is the
path representation scheme used by the **maps** package.)

The length of `layerId` should equal the number of polygons represented in
`lat`/`lng`.

`options` and `defaultOptions` serve the same purpose as `options`/`eachOptions`
in `addCircle` and `addPolygon`, but are not consistent for historical reasons.
This ought to be fixed in a future, compatibility-breaking release.
`defaultOptions` is a list of [path
options](http://leafletjs.com/reference.html#path-options) that will be applied
to all of the polygons. `options` is a list of lists of path options that will
be applied to the corresponding polygon.

## addGeoJSON()

```r
addGeoJSON(data, layerId)
```

Adds GeoJSON to the map. `data` can be either a GeoJSON string (must be a
_single-element_ character vector) or structured GeoJSON data (in the form of
nested lists). The `layerId` is a single-element character vector that refers to
the GeoJSON data in its entirety.

Each GeoJSON feature can include a `style` member, either directly on the
feature object or in the feature object's `properties` member. See [path
options](http://leafletjs.com/reference.html#path-options) to see what style
options are available.

If a GeoJSON feature has an `id` member, that value will be passed back during
events as a `featureId` field on the event object.

Events supported: `input$MAPID_geojson_click`, `input$MAPID_geojson_mouseover`,
and `input$MAPID_geojson_mouseout`.

## clearMarkers()

```r
clearMarkers()
```

Clears all markers currently on the map.

## clearShapes()

```r
clearShapes()
```

Clears all shapes currently on the map.

## showPopup()

```r
showPopup(lat, lng, content, layerId = NULL, options = list())
```

Show a popup at the specified location, with the given content. The content
string will be interpreted as HTML. The argument `options` is a list of [popup
options](http://leafletjs.com/reference.html#popup-options).

## removePopup()

```r
removePopup(layerId)
```

Remove the specified popup.

## clearPopups()

```r
clearPopups()
```

Remove all popups.

# Events

TODO

# Data Sources

Population data is from US Census Bureau:

- http://www.census.gov/popest/data/intercensal/cities/cities2010.html
- http://www.census.gov/popest/data/intercensal/cities/files/SUB-EST00INT.csv

Location data is from USGS:

- http://geonames.usgs.gov/domestic/download_data.htm
- http://geonames.usgs.gov/docs/stategaz/NationalFile_20130602.zip
