# Errors

### ? leaflet


```{r}
m %>% addMarkers(rand_lng(), rand_lat())
# html/css/js errors
# imagesmarker-icon-2x.png Failed to load resource: the server responded with a status of 403 (Forbidden)
# imagesmarker-shadow.png Failed to load resource: the server responded with a status of 403 (Forbidden)
```

error was pre-existing and not caused by 1.0.3
fixed but not solved [commit](https://github.com/timelyportfolio/leaflet/commit/4b841f02c399a206c84642a42e5eb189498f9b65)


### controls

leaflet-measure and layersControl do not remove

not an `v1.0.3` issue but fixed [commit](https://github.com/timelyportfolio/leaflet/commit/c6762e313f268954d8c19225177a991129c20a98) and [commit](https://github.com/timelyportfolio/leaflet/commit/55334c10536f6bc0b7250139e64e262f2cb48c51).  However, none of controls use `ControlStore` mechanism, so would be nice to resolve this on a grander scale.


### labels/tooltips

https://github.com/Leaflet/Leaflet.label#upgrade-path-to-ltooltip

leaflet-label now in main leaflet as L.tooltip.  How do we handle changed options in `labelOptions`?.  Do we just translate `clickable` to `interactive` and `clickable` to `interactive` in R so old examples still work?

**NOTE: starting with Leaflet 1.0, `L.Label` is added to Leaflet core as `L.Tooltip` and this plugin is deprecrated.**

### Upgrade path to L.Tooltip

- `bindLabel`, `openLabel` and so should be replaced by `bindTooltip`, `openTooltip`, etc.
- option `clickable` is now named `interactive`
- option `noHide` is now named `permanent`
- default `offset` is now [6, -6]
- default `direction` is now `auto`
- default `opacity` is now `0.9`
- the CSS has been fully refactored

- Bonus: L.Tooltip also works for paths: polygons, polylines, etc.
- Bonus: new directions are supported: `top`, `bottom`, `center`
- Bonus: new option `sticky` will make the label follow the mouse instead of being displayed at the feature center


# removed leaflet-label source and in yaml in [commit]()
